// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAjL46aTDDKNzt7YxfZ6iRNGPSh1z5iqI',
    appId: '1:246843577822:web:05e02ac2b3b8938153794f',
    messagingSenderId: '246843577822',
    projectId: 'a-maker-2b48b',
    authDomain: 'a-maker-2b48b.firebaseapp.com',
    storageBucket: 'a-maker-2b48b.appspot.com',
    measurementId: 'G-SZEDD6MJ6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4oKM3ZgE1tcEI4Hu00M2y2Vjd_RYWr08',
    appId: '1:246843577822:android:7d1f56df74c167fa53794f',
    messagingSenderId: '246843577822',
    projectId: 'a-maker-2b48b',
    storageBucket: 'a-maker-2b48b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWjXPaGhCPiwJyC8497VQGrEc9NPC4lOI',
    appId: '1:246843577822:ios:d8b705240c7e0dc753794f',
    messagingSenderId: '246843577822',
    projectId: 'a-maker-2b48b',
    storageBucket: 'a-maker-2b48b.appspot.com',
    iosBundleId: 'com.example.aMakerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWjXPaGhCPiwJyC8497VQGrEc9NPC4lOI',
    appId: '1:246843577822:ios:d8b705240c7e0dc753794f',
    messagingSenderId: '246843577822',
    projectId: 'a-maker-2b48b',
    storageBucket: 'a-maker-2b48b.appspot.com',
    iosBundleId: 'com.example.aMakerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAjL46aTDDKNzt7YxfZ6iRNGPSh1z5iqI',
    appId: '1:246843577822:web:0ccdc79408d604e753794f',
    messagingSenderId: '246843577822',
    projectId: 'a-maker-2b48b',
    authDomain: 'a-maker-2b48b.firebaseapp.com',
    storageBucket: 'a-maker-2b48b.appspot.com',
    measurementId: 'G-6ENRKFSGP9',
  );
}
